# Generated by Django 5.1.4 on 2024-12-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_rest_api', '0002_rename_user_id_perfiles_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
