services:
    # mysql:
    #     image: mysql:8.0.40-debian
    #     stdin_open: true
    #     tty: true
    #     ports:
    #         - 8085:80
    #     volumes:
    #       - ./db_storage:/etc/lib/mysql
    #     environment:
    #         - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_secrets
    django-gunicorn:
        #image: localhost/plat_free_gunicorn:9.5-python3.13.1
        volumes:
            - static:/backend/static
            - sqllite_db:/ecommerce_project/db
            - django_logs:/logs
        build:
            dockerfile: ./compose/Dockerfile
            context: ../
        expose:
            - 8000
        restart: always
    nginx:
        build: ./nginx
        volumes:
            - static:/static #this is to make sure /static requests are routed to the shared volumne on host machine where django static files are stored
            - nginx_logs:/var/log/nginx
            - ../frontend/dist:/frontend
        ports:
            - 8080:80
            - 8000:8000
        depends_on:
            - django-gunicorn
        restart: always
volumes:
  static:
  sqllite_db:
  django_logs:
  nginx_logs:

secrets:
  db_secrets:
    file: ./secrets/db_secrets.txt