# Generated by Django 5.1.3 on 2024-12-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfiles',
            old_name='user_id',
            new_name='id_usuario',
        ),
    ]
